<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>passwordbox</description>
   <name>password</name>
   <tag></tag>
   <elementGuidId>cc5bba68-f053-4872-ba6c-587be09404d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtPassword' and @name = 'txtPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPassword</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPassword</value>
   </webElementProperties>
</WebElementEntity>
